linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - revive
    - gofmt
    - gosec
    - misspell
    - unconvert
    - unparam
    - gci

linters-settings:
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/christopher/poof)
    custom-order: true

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0